name: Check

on:
  push:
    branches:
    - master
    - 'refs/pull/*'
    - '!**/deploy'
  pull_request:
    paths: '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: setup properties file
      run: echo -e "auth_client_id=id\nauth_client_secret=secret\nauth_scope_photos=readonly" > muzeiPhotos/googleapi.properties
    - name: check
      run: ./gradlew check -i --build-cache
    - name: xxx
      run: echo "steps=${{ toJson(steps) }} job=${{ toJson(job) }}"
    # - name: notification
    #   uses: xinthink/action-telegram@v0.1-release
    #   with:
    #     botToken: ${{ secrets.TelegramBotToken }}
    #     chatId: ${{ secrets.TelegramTarget }}
    #     jobStatus: ${{ toJson(steps) }}

  notification:
    runs-on: ubuntu-latest
    needs: check
    if: !cancelled()
    steps:
    - name: xxx
      run: echo "steps=${{ toJson(steps) }} job=${{ toJson(job) }}"
    - name: notification
      uses: xinthink/action-telegram@v0.1-release
      with:
        botToken: ${{ secrets.TelegramBotToken }}
        chatId: ${{ secrets.TelegramTarget }}
        jobStatus: ${{ toJson(steps) }}
